# Generated by Django 2.2.6 on 2019-10-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_cup', '0002_auto_20191018_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
